sudo: required
services: 
  - docker 
before_install: 
  - docker build -t taki135/docker-react -f Dockerfile.dev .
script:
  - docker run --rm taki135/docker-react npm run test -- --coverage --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-597041933876"
  bucket-path: "docker-react"
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"

