sudo: required
services: 
  - docker 
before_install: 
  - docker build -t taki135/docker-react -f Dockerfile.dev .
script:
  - docker run taki135/docker-react npm run test -- --coverage --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-597041933876"
  on: 
    branch: main
  access_key_id: 
    secure: $AWS_ACCESS_KEY_ID
  secret_access_key: 
    secure: $AWS_SECRET_ACCESS_KEY

